version: '3'
services:
  task-management-server:
    build:
      context: task-management-backend
      dockerfile: Dockerfile
    image: vinicpires/task-management-backend:2.0
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      ADDITIONAL_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      PROFILE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/todo_database
    links:
      - db
      - task-management-frontend
    depends_on:
      - db
    networks:
      - server
  db:
    image: vinicpires/todo_database:1.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=todo_database
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - ./docker/volume-mysql:/var/lib/mysql
    networks:
      - server
  task-management-frontend:
    build:
      context: task-management-frontend
      dockerfile: Dockerfile
    image: vinicpires/task-management-frontend:2.0
    ports:
      - "4200:4200"
    networks:
      - server
networks:
  server:
    driver: bridge